import { expect, it, vi } from 'vitest';
import { ConversationHistoryController } from '$lib/conversation-history';
import { normalizeConversationPage } from '$lib/store';
import type { Agent } from '$lib/types';
import fixture from '../fixtures/claude-first-continuation.json';

it('bridges backend-produced B-only and C-only heads in the established A controller without resetting its older lane', async () => {
  // Generated by TestClaudeFirstContinuationControllerFixture, including real
  // signed cursors, namespace IDs, and compatible single-file/chain revisions.
  const pages = Object.fromEntries(Object.entries(fixture).map(([key, value]) => [key, normalizeConversationPage(value)]));
  const agent: Agent = {
    relay_id: 'relay-fixture', relay_label: 'Fixture', pane_id: 'relay-fixture::pane-1',
    raw_pane_id: 'pane-1', terminal_id: 'terminal-1', server_session_id: 'primary',
    generation: 1, agent: 'claude', cwd: '/work', project: 'Fixture', status: 'working',
    agent_session_id: '123e4567-e89b-12d3-a456-426614174000',
  };
  let head = 'initial';
  const request = vi.fn(async (_agent: Agent, input: { cursor?: string }) => {
    if (!input.cursor) return pages[head];
    if (input.cursor === pages.latestB.nextCursor) return pages.bridgeB;
    if (input.cursor === pages.initial.nextCursor) return pages.olderA;
    if (input.cursor === pages.latestC.nextCursor) return pages.bridgeC;
    throw new Error('Unexpected backend cursor');
  });
  const controller = new ConversationHistoryController(agent, { request, yieldToBrowser: async () => {} });
  const idle = () => vi.waitFor(() => expect(controller.state.requestPhase).toBe('idle'));
  controller.start();
  await idle();
  expect(controller.state.entries.map(({ text }) => text)).toEqual(['A latest question', 'A latest answer']);
  const revision = controller.state.sourceRevision;
  const oldCursor = controller.state.nextCursor;
  const epoch = controller.state.epoch;
  expect(oldCursor).toBe(pages.initial.nextCursor);
  expect(pages.latestB.entries.map(({ text }) => text)).toEqual(['B question', 'B answer']);
  expect(pages.latestB.entries.some(({ id }) => pages.initial.entries.some((entry) => entry.id === id))).toBe(false);

  head = 'latestB';
  controller.refresh();
  await idle();
  expect(request.mock.calls.map(([, input]) => input.cursor)).toEqual([undefined, undefined, pages.latestB.nextCursor]);
  expect(controller.state.errorCode).toBe('');
  expect(controller.state.latestGapOutstanding).toBe(false);
  expect(controller.state.entries.map(({ text }) => text)).toEqual(['A latest question', 'A latest answer', 'B question', 'B answer']);
  expect(controller.state.sourceRevision).toBe(revision);
  expect(controller.state.nextCursor).toBe(oldCursor);
  expect(controller.state.epoch).toBe(epoch);

  controller.demandOlder();
  await idle();
  expect(request.mock.calls.at(-1)?.[1].cursor).toBe(oldCursor);
  expect(controller.state.beginningReached).toBe(true);
  expect(controller.state.entries.map(({ text }) => text)).toEqual(['A older question', 'A older answer', 'A latest question', 'A latest answer', 'B question', 'B answer']);
  head = 'latestC';
  controller.refresh();
  await idle();
  expect(request.mock.calls.at(-1)?.[1].cursor).toBe(pages.latestC.nextCursor);
  expect(controller.state.sourceRevision).toBe(revision);
  expect(controller.state.entries.slice(-2).map(({ text }) => text)).toEqual(['C question', 'C answer']);
  expect(controller.state.beginningReached).toBe(true);
  expect(controller.state.epoch).toBe(epoch);

  const retained = controller.state.entries;
  head = 'replacement';
  controller.refresh();
  await vi.waitFor(() => expect(controller.state.errorCode).toBe('source_changed'));
  expect(controller.state.entries).toEqual(retained);
});
